apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-catalog-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage