apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: gateway
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "ddnhuy/api-gateway:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: gateway-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      initContainers:
        - name: wait-for-catalogapi
          image: busybox
          command: ['sh', '-c', "until nc -z catalog-api {{ .Values.service.port }}; do echo waiting for postgres; sleep 2; done"]
        - name: wait-for-basketapi
          image: busybox
          command: ['sh', '-c', "until nc -z basket-api {{ .Values.service.port }}; do echo waiting for redis; sleep 2; done"]
        - name: wait-for-orderingapi
          image: busybox
          command: ['sh', '-c', "until nc -z order-api {{ .Values.service.port }}; do echo waiting for discountgrpc; sleep 2; done"]
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config
            items:
              - key: appsettings.json
                path: appsettings.json