apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ReverseProxy": {
        "Routes": {
          "catalog-route": {
            "ClusterId": "catalog-cluster",
            "Match": {
              "Path": "/catalog-service/{**catch-all}"
            },
            "Transforms": [ { "PathPattern": "{**catch-all}" } ]
          },
          "basket-route": {
            "ClusterId": "basket-cluster",
            "Match": {
              "Path": "/basket-service/{**catch-all}"
            },
            "Transforms": [ { "PathPattern": "{**catch-all}" } ]
          },
          "ordering-route": {
            "ClusterId": "ordering-cluster",
            "RateLimiterPolicy": "fixed",
            "Match": {
              "Path": "/ordering-service/{**catch-all}"
            },
            "Transforms": [ { "PathPattern": "{**catch-all}" } ]
          }
        },
        "Clusters": {
          "catalog-cluster": {
            "Destinations": {
              "default": {
                "Address": "http://catalog-api:80"
              }
            }
          },
          "basket-cluster": {
            "Destinations": {
              "default": {
                "Address": "http://basket-api:80"
              }
            }
          },
          "ordering-cluster": {
            "Destinations": {
              "default": {
                "Address": "http://ordering-api:80"
              }
            }
          }
        }
      }
    }