apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discount-config
  namespace: eshop
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "Database": "Data Source=/app/data/discount.db"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Information"
        }
      },
      "AllowedHosts": "*",
      "Kestrel": {
        "EndpointDefaults": {
          "Protocols": "Http2"
        }
      }
    }