apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: eshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
        - name: catalog-api
          image: ddnhuy/catalog-api
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-catalog-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres-catalog 5432; do echo waiting for postgres; sleep 2; done']
      volumes:
        - name: config-volume
          configMap:
            name: service-catalog-config
            items:
              - key: appsettings.json
                path: appsettings.json