apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: eshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ddnhuy/api-gateway
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-gateway-config
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      initContainers:
        - name: wait-for-catalogapi
          image: busybox
          command: ['sh', '-c', 'until nc -z catalog-api 8080; do echo waiting for postgres; sleep 2; done']
        - name: wait-for-basketapi
          image: busybox
          command: ['sh', '-c', 'until nc -z basket-api 8080; do echo waiting for redis; sleep 2; done']
        - name: wait-for-orderingapi
          image: busybox
          command: ['sh', '-c', 'until nc -z order-api 8080; do echo waiting for discountgrpc; sleep 2; done']
      volumes:
        - name: config-volume
          configMap:
            name: service-gateway-config
            items:
              - key: appsettings.json
                path: appsettings.json