apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          args: ["--save", "60", "1", "--loglevel", "warning"]
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc