apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discount-pvc
  namespace: eshop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath