apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: eshop
spec:
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP