apiVersion: v1
kind: Service
metadata:
  name: discount-grpc
  namespace: eshop
spec:
  selector:
    app: discount-grpc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP