apiVersion: v1
kind: Service
metadata:
  name: basket-api
spec:
  selector:
    app: basket-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      name: http
      targetPort: 8080
  type: {{ .Values.service.type }}